# Generated by Django 3.2.9 on 2021-11-20 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=25)),
                ('model', models.CharField(default='', max_length=25)),
            ],
            options={
                'verbose_name_plural': 'cars',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, '1-Trash'), (2, '2 - Horrible'), (3, '3 - OK'), (4, '4 - GOOD'), (5, '5 - PERF')])),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars_api.car')),
            ],
        ),
    ]
