# Generated by Django 3.2.9 on 2021-11-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=25)),
                ('model', models.CharField(default='', max_length=25)),
                ('rank', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'cars',
            },
        ),
    ]
