# Generated by Django 3.2.9 on 2021-11-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rank',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
