# Generated by Django 3.2.9 on 2021-11-19 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name_plural': 'cars'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
    ]
