# Generated by Django 3.2.9 on 2021-11-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0002_alter_car_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rank',
            field=models.IntegerField(default=5),
        ),
    ]
